---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <your-managed-identity-client-id>
  labels:
    azure.workload.identity/use: "true"
  name: secretrotator-sa
  namespace: secretrotator
